name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bison \
          flex \
          libgmp3-dev \
          libmpc-dev \
          libmpfr-dev \
          texinfo \
          nasm \
          grub-pc-bin \
          xorriso \
          qemu-system-x86 \
          wget \
          curl

    - name: Build and Install Cross Compiler (C and C++)
      run: |
        export TARGET=i686-elf
        export PREFIX="$HOME/opt/cross"
        export PATH="$PREFIX/bin:$PATH"
        
        mkdir -p $HOME/src
        cd $HOME/src

        # Download binutils
        wget https://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.xz
        tar -xf binutils-2.41.tar.xz

        mkdir build-binutils
        cd build-binutils
        ../binutils-2.41/configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
        make -j$(nproc)
        make install
        cd ..

        # Download GCC
        wget https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz
        tar -xf gcc-13.2.0.tar.xz

        mkdir build-gcc
        cd build-gcc
        ../gcc-13.2.0/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c,c++ --without-headers
        make all-gcc -j$(nproc)
        make all-target-libgcc -j$(nproc)
        make install-gcc
        make install-target-libgcc
        cd ..

    - name: Build ISO
      run: |
        export PATH="$HOME/opt/cross/bin:$PATH"
        make

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ironic-os-iso
        path: build/*.iso